server:
  port: 8080
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

  tomcat:
    threads:
      max: 200

spring:
  application:
    name: "coin-sensor"

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나의 최대 크기
      max-request-size: 20MB # 요청 전체 크기 (여러 파일 포함 가능)

  jpa:
    open-in-view: false
    properties:
      hibernate:
        auto_quote_keyword: true    # SQL 키워드를 자동으로 인용하여 SQL 구문 오류를 방지합니다.

logging:
  file:
    path: ./logs


